name: Build/release

on: 
  push:
   tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v2
      

            - name: Compile Electron App
              uses: helpforsoftware/action-electron-compiler-byforce@v1.1.8
              with:
                #work with v1.1.3
                  # GitHub token, automatically provided to the action
                  # (Optional)
                  github_token: ${{ secrets.github_token }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # (Optional)
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}

                  # Package manager. NPM, PNPM and Yarn supported. Install Yarn and PNPM yourself. Default is NPM
                  # (Optional)
                  package_manager: NPM

                  # Skip buiding the application
                  # (Optional)
                  skip_build: false
            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@2.9.0
              with:
                # A personal access token for the GitHub repository in which the release will be created and edited.
                # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
                repo_token: ${{ secrets.GITHUB_TOKEN  }}
                file: target/dist/Git*.exe
                asset_name: mything
                tag: ${{ github.ref }}
                overwrite: true
                body: "This is my release text"      

               